plugins {
    id("io.papermc.paperweight.userdev")
}

group = 'com.artillexstudios.axapi.nms.v26_1'
version = rootProject.version

repositories {
    mavenLocal()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

reobfJar {
    enabled = false
}


dependencies {
    paperweight.paperDevBundle("26.1.1.build.+")
}