package com.artillexstudios.axapi.particle;

import com.artillexstudios.axapi.packet.FriendlyByteBuf;
import com.artillexstudios.axapi.particle.option.DustColorTransitionParticleOption;
import com.artillexstudios.axapi.particle.option.DustParticleOption;
import com.artillexstudios.axapi.particle.option.FloatParticleOption;
import com.artillexstudios.axapi.particle.option.IntegerParticleOption;
import com.artillexstudios.axapi.particle.option.ItemStackParticleOption;
import com.artillexstudios.axapi.particle.option.TrailParticleOption;
import com.artillexstudios.axapi.particle.option.VibrationParticleOption;
import com.artillexstudios.axapi.particle.type.DustColorTransitionParticleType;
import com.artillexstudios.axapi.particle.type.DustParticleType;
import com.artillexstudios.axapi.particle.type.FloatParticleType;
import com.artillexstudios.axapi.particle.type.IntegerParticleType;
import com.artillexstudios.axapi.particle.type.ItemStackParticleType;
import com.artillexstudios.axapi.particle.type.TrailParticleType;
import com.artillexstudios.axapi.particle.type.VarIntParticleType;
import com.artillexstudios.axapi.particle.type.SimpleParticleType;
import com.artillexstudios.axapi.particle.type.VibrationParticleType;
import it.unimi.dsi.fastutil.ints.Int2ObjectArrayMap;

public final class ParticleTypes {
    private static final Int2ObjectArrayMap<ParticleType<?>> registry = new Int2ObjectArrayMap<>();
    public static ParticleType<?> ANGRY_VILLAGER = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> BLOCK = register(new VarIntParticleType());
    public static ParticleType<IntegerParticleOption> BLOCK_MARKER = register(new VarIntParticleType());
    public static ParticleType<?> BUBBLE = register(new SimpleParticleType());
    public static ParticleType<?> CLOUD = register(new SimpleParticleType());
    public static ParticleType<?> CRIT = register(new SimpleParticleType());
    public static ParticleType<?> DAMAGE_INDICATOR = register(new SimpleParticleType());
    public static ParticleType<?> DRAGON_BREATH = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_LAVA = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_LAVA = register(new SimpleParticleType());
    public static ParticleType<?> LANDING_LAVA = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_WATER = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_WATER = register(new SimpleParticleType());
    public static ParticleType<DustParticleOption> DUST = register(new DustParticleType());
    public static ParticleType<DustColorTransitionParticleOption> DUST_COLOR_TRANSITION = register(new DustColorTransitionParticleType());
    public static ParticleType<?> EFFECT = register(new SimpleParticleType());
    public static ParticleType<?> ELDER_GUARDIAN = register(new SimpleParticleType());
    public static ParticleType<?> ENCHANTED_HIT = register(new SimpleParticleType());
    public static ParticleType<?> ENCHANT = register(new SimpleParticleType());
    public static ParticleType<?> END_ROD = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> ENTITY_EFFECT = register(new IntegerParticleType());
    public static ParticleType<?> EXPLOSION_EMITTER = register(new SimpleParticleType());
    public static ParticleType<?> EXPLOSION = register(new SimpleParticleType());
    public static ParticleType<?> GUST = register(new SimpleParticleType());
    public static ParticleType<?> SMALL_GUST = register(new SimpleParticleType());
    public static ParticleType<?> GUST_EMITTER_LARGE = register(new SimpleParticleType());
    public static ParticleType<?> SONIC_BOOM = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> FALLING_DUST = register(new VarIntParticleType());
    public static ParticleType<?> FIREWORK = register(new SimpleParticleType());
    public static ParticleType<?> FISHING = register(new SimpleParticleType());
    public static ParticleType<?> FLAME = register(new SimpleParticleType());
    public static ParticleType<?> INFESTED = register(new SimpleParticleType());
    public static ParticleType<?> CHERRY_LEAVES = register(new SimpleParticleType());
    public static ParticleType<?> PALE_OAK_LEAVES = register(new SimpleParticleType());
    public static ParticleType<?> SCULK_SOUL = register(new SimpleParticleType());
    public static ParticleType<FloatParticleOption> SCULK_CHARGE = register(new FloatParticleType());
    public static ParticleType<?> SCULK_CHARGE_POP = register(new SimpleParticleType());
    public static ParticleType<?> SOUL_FIRE_FLAME = register(new SimpleParticleType());
    public static ParticleType<?> SOUL = register(new SimpleParticleType());
    public static ParticleType<?> FLASH = register(new SimpleParticleType());
    public static ParticleType<?> HAPPY_VILLAGER = register(new SimpleParticleType());
    public static ParticleType<?> COMPOSTER = register(new SimpleParticleType());
    public static ParticleType<?> HEART = register(new SimpleParticleType());
    public static ParticleType<?> INSTANT_EFFECT = register(new SimpleParticleType());
    public static ParticleType<ItemStackParticleOption> ITEM = register(new ItemStackParticleType());
    public static ParticleType<VibrationParticleOption> VIBRATION = register(new VibrationParticleType());
    public static ParticleType<TrailParticleOption> TRAIL = register(new TrailParticleType());
    public static ParticleType<?> ITEM_SLIME = register(new SimpleParticleType());
    public static ParticleType<?> ITEM_COBWEB = register(new SimpleParticleType());
    public static ParticleType<?> ITEM_SNOWBALL = register(new SimpleParticleType());
    public static ParticleType<?> LARGE_SMOKE = register(new SimpleParticleType());
    public static ParticleType<?> LAVA = register(new SimpleParticleType());
    public static ParticleType<?> MYCELIUM = register(new SimpleParticleType());
    public static ParticleType<?> NOTE = register(new SimpleParticleType());
    public static ParticleType<?> POOF = register(new SimpleParticleType());
    public static ParticleType<?> PORTAL = register(new SimpleParticleType());
    public static ParticleType<?> RAIN = register(new SimpleParticleType());
    public static ParticleType<?> SMOKE = register(new SimpleParticleType());
    public static ParticleType<?> WHITE_SMOKE = register(new SimpleParticleType());
    public static ParticleType<?> SNEEZE = register(new SimpleParticleType());
    public static ParticleType<?> SPIT = register(new SimpleParticleType());
    public static ParticleType<?> SQUID_INK = register(new SimpleParticleType());
    public static ParticleType<?> SWEEP_ATTACK = register(new SimpleParticleType());
    public static ParticleType<?> TOTEM_OF_UNDYING = register(new SimpleParticleType());
    public static ParticleType<?> UNDERWATER = register(new SimpleParticleType());
    public static ParticleType<?> SPLASH = register(new SimpleParticleType());
    public static ParticleType<?> WITCH = register(new SimpleParticleType());
    public static ParticleType<?> BUBBLE_POP = register(new SimpleParticleType());
    public static ParticleType<?> CURRENT_DOWN = register(new SimpleParticleType());
    public static ParticleType<?> BUBBLE_COLUMN_UP = register(new SimpleParticleType());
    public static ParticleType<?> NAUTILUS = register(new SimpleParticleType());
    public static ParticleType<?> DOLPHIN = register(new SimpleParticleType());
    public static ParticleType<?> CAMPFIRE_COSY_SMOKE = register(new SimpleParticleType());
    public static ParticleType<?> CAMPFIRE_SIGNAL_SMOKE = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_HONEY = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_HONEY = register(new SimpleParticleType());
    public static ParticleType<?> LANDING_HONEY = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_NECTAR = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_SPORE_BLOSSOM = register(new SimpleParticleType());
    public static ParticleType<?> ASH = register(new SimpleParticleType());
    public static ParticleType<?> CRIMSON_SPORE = register(new SimpleParticleType());
    public static ParticleType<?> WARPED_SPORE = register(new SimpleParticleType());
    public static ParticleType<?> SPORE_BLOSSOM_AIR = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_OBSIDIAN_TEAR = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_OBSIDIAN_TEAR = register(new SimpleParticleType());
    public static ParticleType<?> LANDING_OBSIDIAN_TEAR = register(new SimpleParticleType());
    public static ParticleType<?> REVERSE_PORTAL = register(new SimpleParticleType());
    public static ParticleType<?> WHITE_ASH = register(new SimpleParticleType());
    public static ParticleType<?> SMALL_FLAME = register(new SimpleParticleType());
    public static ParticleType<?> SNOWFLAKE = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_DRIPSTONE_LAVA = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_DRIPSTONE_LAVA = register(new SimpleParticleType());
    public static ParticleType<?> DRIPPING_DRIPSTONE_WATER = register(new SimpleParticleType());
    public static ParticleType<?> FALLING_DRIPSTONE_WATER = register(new SimpleParticleType());
    public static ParticleType<?> GLOW_SQUID_INK = register(new SimpleParticleType());
    public static ParticleType<?> GLOW = register(new SimpleParticleType());
    public static ParticleType<?> WAX_ON = register(new SimpleParticleType());
    public static ParticleType<?> WAX_OFF = register(new SimpleParticleType());
    public static ParticleType<?> ELECTRIC_SPARK = register(new SimpleParticleType());
    public static ParticleType<?> SCRAPE = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> SHRIEK = register(new VarIntParticleType());
    public static ParticleType<?> EGG_CRACK = register(new SimpleParticleType());
    public static ParticleType<?> DUST_PLUME = register(new SimpleParticleType());
    public static ParticleType<?> TRIAL_SPAWNER_DETECTION = register(new SimpleParticleType());
    public static ParticleType<?> TRIAL_SPAWNER_DETECTION_OMINOUS = register(new SimpleParticleType());
    public static ParticleType<?> VAULT_CONNECTION = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> DUST_PILLAR = register(new VarIntParticleType());
    public static ParticleType<?> OMINOUS_SPAWNING = register(new SimpleParticleType());
    public static ParticleType<?> RAID_OMEN = register(new SimpleParticleType());
    public static ParticleType<?> TRIAL_OMEN = register(new SimpleParticleType());
    public static ParticleType<IntegerParticleOption> BLOCK_CRUMBLE = register(new VarIntParticleType());


    public static <T extends ParticleOption> ParticleData<T> read(FriendlyByteBuf buf) {
        int id = buf.readVarInt();
        ParticleType<T> type = (ParticleType<T>) registry.get(id);
        return new ParticleData<>(type, type.read(buf));
    }

    public static <T extends ParticleOption> ParticleType<T> register(ParticleType<T> type) {
        registry.put(registry.size(), type);
        return type;
    }
}
